version: "3.9"
services:
  streamlit-app:
    build:
      context: ".."
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    #environment:
    #  - PSQL_HOST=${PSQL_HOST}
    #  - PSQL_PORT=${PSQL_PORT}
    ports:
      - "8501:8501"
    volumes:
       # Mounting this file allows updates to the webpage without restarting the container
      - ./:/app/

